import Head from "next/head";
import Image from "next/image";
import { Button } from "../components";
import { Companies } from "../components/companies/Companies";
import { Navbar } from "../components/navbar/Navbar";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.main_container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <main className={styles.main}>
        <section className={styles.padding_block}>
          <div className={styles.even_columns}>
            <div className={styles.hero_text}>
              <h1 className={styles.hero_title}>Make remote work</h1>
              <p>
                Get your team in sync, no matter your location. Streamline
                processes, create team rituals, and watch productivity soar.
              </p>
              <Button title={"Learn more"} />
              <Companies />
            </div>
            <div className={styles.hero_image}>
              <Image
                src={"/image-hero-desktop.png"}
                alt="Hero Image"
                width={580}
                height={700}
              />
            </div>
          </div>
        </section>
      </main>
      <footer className={styles.footer}>
        <span className={styles.logo}>
          <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
        </span>
      </footer>
    </div>
  );
}
